"""
Tool registry — defines Claude API tool schemas and the dispatcher.
Agents import TOOL_SCHEMAS for their API calls and call dispatch() on results.
"""

import json
from tools.file_tools        import (read_feature_file, write_test_file,
                                      list_feature_files, list_generated_tests,
                                      read_generated_file)
from tools.gherkin_validator  import validate_gherkin, extract_scenario_titles
from tools.coverage_calculator import calculate_coverage


# ── Claude API tool schemas ────────────────────────────────────────────────────

TOOL_SCHEMAS = [
    {
        "name": "read_feature_file",
        "description": (
            "Read a maritime feature description file from the sample_features/ directory. "
            "Use this to load the feature text before starting analysis."
        ),
        "input_schema": {
            "type": "object",
            "properties": {
                "filename": {
                    "type": "string",
                    "description": "Filename including .txt extension, e.g. 'crew_certification.txt'",
                }
            },
            "required": ["filename"],
        },
    },
    {
        "name": "list_feature_files",
        "description": "List all available maritime feature description files in sample_features/.",
        "input_schema": {
            "type": "object",
            "properties": {},
            "required": [],
        },
    },
    {
        "name": "validate_gherkin",
        "description": (
            "Validate a Gherkin BDD feature text for structural correctness. "
            "Checks Feature/Scenario/Given/When/Then syntax, counts scenarios, "
            "identifies missing safety tags, and returns quality metrics. "
            "Always call this after generating Gherkin to verify it is valid."
        ),
        "input_schema": {
            "type": "object",
            "properties": {
                "gherkin_text": {
                    "type": "string",
                    "description": "The full Gherkin feature text to validate.",
                }
            },
            "required": ["gherkin_text"],
        },
    },
    {
        "name": "calculate_coverage",
        "description": (
            "Map generated Gherkin scenarios against the extracted requirements list "
            "to calculate test coverage percentage. Identifies uncovered requirements, "
            "safety-critical gaps, compliance-related gaps, and missing edge cases. "
            "Call this after Gherkin is validated to produce the coverage gap report."
        ),
        "input_schema": {
            "type": "object",
            "properties": {
                "requirements": {
                    "type": "array",
                    "items": {"type": "string"},
                    "description": "List of requirements extracted from the feature description.",
                },
                "scenarios": {
                    "type": "array",
                    "items": {"type": "string"},
                    "description": "List of Gherkin scenario titles generated by the BDD Generator.",
                },
                "feature_name": {
                    "type": "string",
                    "description": "Name of the feature being analysed, e.g. 'Crew Certification Expiry'.",
                },
            },
            "required": ["requirements", "scenarios"],
        },
    },
    {
        "name": "write_test_file",
        "description": (
            "Write a generated test file to the outputs/ directory. "
            "Use file_type='feature' for Gherkin (.feature files), "
            "'playwright' for Playwright TypeScript specs (.spec.ts files), "
            "or 'report' for JSON coverage/audit reports."
        ),
        "input_schema": {
            "type": "object",
            "properties": {
                "filename": {
                    "type": "string",
                    "description": "Base filename without extension, e.g. 'crew_certification'.",
                },
                "content": {
                    "type": "string",
                    "description": "The full text content to write to the file.",
                },
                "file_type": {
                    "type": "string",
                    "enum": ["feature", "playwright", "report"],
                    "description": "Type of file: 'feature', 'playwright', or 'report'.",
                },
            },
            "required": ["filename", "content", "file_type"],
        },
    },
    {
        "name": "list_generated_tests",
        "description": "List all previously generated test files in generated_tests/.",
        "input_schema": {
            "type": "object",
            "properties": {},
            "required": [],
        },
    },
]


# ── Dispatcher ─────────────────────────────────────────────────────────────────

def dispatch(tool_name: str, tool_input: dict) -> str:
    """
    Execute a tool by name and return its result as a JSON string.
    Called by agents inside their tool-use loop.
    """
    handlers = {
        "read_feature_file":   lambda i: read_feature_file(i["filename"]),
        "list_feature_files":  lambda i: list_feature_files(),
        "validate_gherkin":    lambda i: validate_gherkin(i["gherkin_text"]),
        "calculate_coverage":  lambda i: calculate_coverage(
                                   i["requirements"],
                                   i["scenarios"],
                                   i.get("feature_name", ""),
                               ),
        "write_test_file":     lambda i: write_test_file(
                                   i["filename"],
                                   i["content"],
                                   i.get("file_type", "feature"),
                               ),
        "list_generated_tests": lambda i: list_generated_tests(),
        "read_generated_file":  lambda i: read_generated_file(i["filename"]),
    }

    handler = handlers.get(tool_name)
    if not handler:
        return json.dumps({"error": f"Unknown tool: '{tool_name}'"})

    try:
        result = handler(tool_input)
        return json.dumps(result, ensure_ascii=False, indent=2)
    except Exception as exc:
        return json.dumps({"error": str(exc), "tool": tool_name})
